name: parserflow
description: >
  An experimental parsing library
version: 0.0.1
author: PLATEL Kevin <platel.kevin@gmail.com>
#homepage: https://www.example.com
dependencies:
  logging: any
dev_dependencies:
  test: any
  unittest: any
